#ifndef CONFIG_H
#define CONFIG_H

/* Debug UART (BAS02) */
#define DEBUG_UART_HANDLE        huart2  /* UART handle name generated by CubeMX */
#define DEBUG_UART_BUFFER_SIZE   128U    /* max characters per Debug_Printf call */
#define DEBUG_UART_TIMEOUT_MS    100U    /* max wait for one transmit */

/* Test loop */
#define HEARTBEAT_PERIOD_MS      1000U   /* time between debug messages */

#endif /* CONFIG_H */